# -*- coding: utf-8 -*-
"""Quant_Finance_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2TI9RV3IRXWf2l2MLQ32dHMhv5YG4tv
"""


import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
#
# Montecarlo simulation Function
#
def simulate_paths(S0, r, sigma, T, steps, n_simulations):
  steps = int(steps)
  n_simulations = int(n_simulations)  
    
  dt=T/steps
  paths = np.zeros((n_simulations,steps))

  for i in range(n_simulations):
    
    for t in range(1,steps):
      Z = np.random.normal()
      S_t = prices[-1] * np.exp((r - 0.5 * sigma**2)
      * dt + sigma * np.sqrt(dt) * Z )
      

      
  return paths

  #
  # Asian Option Pricing
  #

def asian_option_price(S0, K, r, sigma, T, steps, n_simulations):
    paths=simulate_paths(S0, r, sigma, T, steps, n_simulations)

    avg_prices= np.mean(paths, axis=1)
    payoffs= np.maximum(avg_prices - K,0)

    price = np.exp(-r * T) *np.mean(payoffs)
    return price, paths

  #
  # Streamlit UI
  #

st.set_page_config(page_title="Exotic Option App", layout="centered")

st.title("📊 Exotic Option Pricing & Abitrage Detector")
st.write("Monte Carlo Simulation of Asian Option")

  #
  # Inputs
  #

S0 = st.number_input("Initial Stock Price (S0)", value = 100.0)
K = st.number_input("Strike Price (K)", value = 100.0)
r = st.number_input("Risk-Free Rate (r)", value = 0.05)
sigma = st.number_input("Volatility (σ)", value = 0.2)
T = st.number_input("Time to Maturity (years)", value = 1.0)
steps = st.slider("Time Steps", 10, 300, 100)
n_simulations = st.slider("Number of Simulations", 1000, 50000, 10000)

st.subheader("Market Comparison")
market_price = st.number_input("Market Option Price", value = 10.0)
transaction_cost = st.number_input("Transaction Cost", value=0.5)

#
# Run Simulation
#

if st.button("Run Simulation"):

    price, paths = asian_option_price(
        S0, K, r, sigma, T, steps, n_simulations
    )

    st.success(f"📈 Model Price: {price:.4f}")

#
# Abitrage Detection
#

    mispricing = market_price - price
    real_profit = mispricing - transaction_cost

    st.subheader("🔍 Arbitrage Analysis")

    st.write(f"Mispricing: {mispricing:.4f}")
    st.write(f"Profit After Costs: {real_profit:.4f}")

    if real_profit > 0:
        st.error("🚨 Arbitrage Opportunity Detected!")
    elif mispricing > 0:
        st.warning("⚠️ Slight mispricing, but not profitable after costs")
    else:
        st.success("✅ No arbitrage opportunity")

  #
  # Opportunity Strength
  #

    st.subheader("🤖 Opportunity Strength")

    if abs(mispricing) > 5:
        st.write("🔥 Strong opportunity")
    elif abs(mispricing) > 1:
        st.write("⚡ Medium opportunity")
    else:
        st.write("❌ Weak / No opportunity")


    #
    # Plot Simulated Paths
    #

    st.subheader("📉 Simulated Price Paths")

    fig, ax = plt.subplots()

    for i in range(min(20, len(paths))):
        ax.plot(paths[i], linewidth=1)

    ax.set_title("Monte Carlo Simulated Paths")
    ax.set_xlabel("Time Steps")
    ax.set_ylabel("Price")

    st.pyplot(fig)

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

# -------------------------------
# Monte Carlo Simulation
# -------------------------------

def simulate_paths(S0, r, sigma, T, steps, n_simulations):
    dt = T / steps
    paths = np.zeros((n_simulations, steps))

    for i in range(n_simulations):
        prices = [S0]
        for t in range(1, steps):
            Z = np.random.normal()
            S_t = prices[-1] * np.exp(
                (r - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * Z
            )
            prices.append(S_t)
        paths[i] = prices

    return paths


# -------------------------------
# Asian Option Pricing
# -------------------------------

def asian_option_price(S0, K, r, sigma, T, steps, n_simulations):
    paths = simulate_paths(S0, r, sigma, T, steps, n_simulations)
    avg_prices = np.mean(paths, axis=1)
    payoffs = np.maximum(avg_prices - K, 0)
    price = np.exp(-r * T) * np.mean(payoffs)
    return price, paths


# -------------------------------
# Interactive App
# -------------------------------

def run_app(S0=100, K=100, r=0.05, sigma=0.2, T=1,
            steps=100, n_simulations=5000,
            market_price=10, transaction_cost=0.5):

    price, paths = asian_option_price(S0, K, r, sigma, T, steps, n_simulations)

    print("📊 MODEL RESULTS")
    print("----------------------------")
    print(f"Model Price: {price:.4f}")

    # Arbitrage
    mispricing = market_price - price
    real_profit = mispricing - transaction_cost

    print("\n🔍 ARBITRAGE ANALYSIS")
    print("----------------------------")
    print(f"Market Price: {market_price}")
    print(f"Mispricing: {mispricing:.4f}")
    print(f"Profit after costs: {real_profit:.4f}")

    if real_profit > 0:
        print("🚨 Arbitrage Opportunity!")
    elif mispricing > 0:
        print("⚠️ Not profitable after costs")
    else:
        print("✅ No arbitrage")

    # Strength
    print("\n🤖 OPPORTUNITY STRENGTH")
    print("----------------------------")
    if abs(mispricing) > 5:
        print("🔥 Strong opportunity")
    elif abs(mispricing) > 1:
        print("⚡ Medium opportunity")
    else:
        print("❌ Weak/No opportunity")

    # Plot
    plt.figure(figsize=(10,5))
    for i in range(20):
        plt.plot(paths[i], linewidth=1)

    plt.title("Monte Carlo Simulated Price Paths")
    plt.xlabel("Time Steps")
    plt.ylabel("Price")
    plt.show()


# -------------------------------
# Interactive Sliders
# -------------------------------

interact(run_app,
         S0=(50, 200, 5),
         K=(50, 200, 5),
         r=(0.0, 0.1, 0.01),
         sigma=(0.1, 0.5, 0.05),
         T=(0.5, 2.0, 0.5),
         steps=(50, 200, 10),
         n_simulations=(1000, 20000, 1000),
         market_price=(1, 30, 1),
         transaction_cost=(0.0, 2.0, 0.1)
)
